apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-sample
spec:
  filters:
  - parser:
      parse:
        type: multi_format
        patterns:
        - format: nginx
        - format: regexp
          expression: /^\[(?<logtime>[^\]]*)\] (?<name>[^ ]*) (?<title>[^ ]*) (?<id>\d*)$/
        - format: none
      remove_key_name_field: true
      reserve_data: true
  localOutputRefs:
  - s3-output
  match:
    - select:
        labels:
          app.kubernetes.io/instance: nginx-demo
          app.kubernetes.io/name: nginx-logging-demo
