apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-sample
  namespace: default
spec:
  localOutputRefs:
    - gcs-output-sample
    - s3-output-example
  match:
    - select:
        labels:
          app: nginx
