apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: forward-output-sample
spec:
  forward:
    servers:
      - host: 127.0.0.1
        port: 24240
    tls_cert_path:
      mountFrom:
        secretKeyRef:
          name: fluentd-tls
          key: tls.crt
    buffer:
      timekey: 1m
      timekey_wait: 10s
      timekey_use_utc: true
