apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: logging-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logging-operator
    spec:
      containers:
        - name: logging-operator
          image: "kube-logging/logging-operator:latest"
          imagePullPolicy: IfNotPresent
          resources:
            {}
      serviceAccountName: logging-operator
